version: '3.5'

services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli -m 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' --db='/chaindata' --defaultBalanceEther 10000 --account="0xdad57e191799c38233bb7897f5ca66eb42d4f2f6d05ec657f8121b57e5d3bde6, 1000000000000000000000" --account="0x5aaa244692f54da4335a8553249b0db34316fbbc6ec353e1404cf77c415e59e8, 1000000000000000000000" --account="0x70441f8ed88f91416fbe21aa007357354e9bc30236211eda0022bdfb27beb227, 1000000000000000000000" --account="0x9ff4f711a85ed35d2cc66323abcd83f41e5981e0cd395800a262beb9a92b8abf, 1000000000000000000000" --account="0x77e701995d56e775bbb06559ece7d7352157106bbadc6aa5d8781c86c8d824bd, 1000000000000000000000" --networkId '333' --gasLimit 10000000
    ports:
      - 8545:8545
    networks:
      - network-supplier1
    volumes:
      - chaindata:/chaindata

  deploy:
    build:
      context: ./deploy/
    depends_on:
      - ganache
      - messenger-MESSENGER_SUPPLIER1_URI
      - mongo-supplier1
      - zkp
    environment:
      RPC_PROVIDER: http://ganache:8545
      MESSENGER_SUPPLIER1_URI: http://messenger-supplier1:4001
      ZKP_URL: http://zkp:80
    networks:
      - network-supplier1
    volumes:
      - ./deploy/src:/app/src:delegated
      - ./deploy/package.json:/app/package.json:delegated
      - ./contracts/artifacts:/app/artifacts:delegated
      - ./config/keystore:/keystore:delegated
      - ./config:/app/src/config


